Timewave z3r0: twz-generator-threaded.c File Reference
twz-generator-threaded.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include <pthread.h>
#include "DATA/DATA.TW1"
#include "DATA/DATA.TW2"
#include "DATA/DATA.TW3"
#include "DATA/DATA.TW4"
Data Structures
struct ThreadStruct
Macros
#define CALC_PREC 1000000
#define FALSE 0
#define NUM_DATA_POINTS 384
#define NUM_POWERS 64
#define NUM_SETS 4
#define PREC 16
#define TRUE 1
Functions
long double div_power (long double x, int64_t i)
int64_t doublecheck (void)
long double f (long double x, int64_t number_set)
void * fFOUR (void)
void * fONE (void)
void * fTHREE (void)
void * fTWO (void)
void get_dtzp (void)
void get_NegBailout (void)
void get_step (void)
void get_wave_factor (void)
void inputerror (void)
int main (int argc, char *argv[])
long double mult_power (long double x, int64_t i)
void set_powers (void)
long double v (long double y, int64_t number_set)
Variables
long double dtzp
struct ThreadStruct lockstruct
Create a global lock structure to ease programming (4 static threads, so this is OK)
long double NegativeBailout = -2.0
int64_t number_set
long double powers [NUM_POWERS]
char * set_name [NUM_SETS]
long double step
int64_t stringchar
char * title = "Days to Zero (DTZ), Kelley, Watkins, Sheliak, Huang Ti"
char * usage
int64_t w [NUM_SETS][NUM_DATA_POINTS]
int64_t wave_factor = 64
Macro Definition Documentation
CALC_PREC
#define CALC_PREC 1000000
Definition at line 69 of file twz-generator-threaded.c.
Referenced by f(), fFOUR(), fONE(), fTHREE(), and fTWO().
FALSE
#define FALSE 0
Definition at line 62 of file twz-generator-threaded.c.
NUM_DATA_POINTS
#define NUM_DATA_POINTS 384
Definition at line 68 of file twz-generator-threaded.c.
Referenced by v().
NUM_POWERS
#define NUM_POWERS 64
Definition at line 64 of file twz-generator-threaded.c.
Referenced by set_powers().
NUM_SETS
#define NUM_SETS 4
Definition at line 67 of file twz-generator-threaded.c.
PREC
#define PREC 16
Definition at line 65 of file twz-generator-threaded.c.
Referenced by main().
TRUE
#define TRUE 1
Definition at line 63 of file twz-generator-threaded.c.
Function Documentation
div_power()
long double div_power (long double x, int64_t i)
Definition at line 506 of file twz-generator-threaded.c.
References powers.
Referenced by f(), fFOUR(), fONE(), fTHREE(), and fTWO().
 {
     /* Removing this code: Switching to 64-bit datatypes
     int64_t *exponent = (int64_t *) &x + 3;
     if ((wave_factor == 64) && (*exponent > i * 0x60))
         *exponent -= i * 0x60;
     else */
         x /= powers[i];
     return (x);
 }
doublecheck()
int64_t doublecheck (void)
Definition at line 555 of file twz-generator-threaded.c.
References dtzp, and step.
 {
     char answer;
     printf("\nThe combination you have chosen will create %Lf data points. \nDo you wish to continue? (Y/N) ", 1 + (int) dtzp / step);
     answer = getchar ();
 }
f()
long double f (long double x, int64_t number_set)
Definition at line 246 of file twz-generator-threaded.c.
References CALC_PREC, div_power(), mult_power(), powers, and v().
 {
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
             last_sum = sum;
             sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
     }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     return (sum);
 }
fFOUR()
void * fFOUR (void)
Definition at line 421 of file twz-generator-threaded.c.
References ThreadStruct::_lock4, ThreadStruct::ans4, CALC_PREC, div_power(), lockstruct, mult_power(), number_set, powers, v(), and ThreadStruct::x4.
Referenced by main().
 {
     fourstart:
     ;           // This semicolon is required on GCC and ignored elsewhere
     // Wait until the lock is un-set, then run
     do {
         // Do Nothing
     } while (false == lockstruct._lock4);
     int64_t number_set = 3;
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     long double x = lockstruct.x4;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
         last_sum = sum;
         sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
     }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     // Done : Reset everything for next run
     lockstruct.ans4 = sum;
     lockstruct._lock4 = false;
     goto fourstart;
     return 0;
 }
fONE()
void * fONE (void)
Definition at line 280 of file twz-generator-threaded.c.
References ThreadStruct::_lock1, ThreadStruct::ans1, CALC_PREC, div_power(), lockstruct, mult_power(), number_set, powers, v(), and ThreadStruct::x1.
Referenced by main().
 {
     onestart:
     ;           // This semicolon is required on GCC and ignored elsewhere
     // Wait until the lock is un-set, then run
     do {
         // Do Nothing
     } while (false == lockstruct._lock1);
     int64_t number_set = 0;
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     long double x = lockstruct.x1;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
         last_sum = sum;
         sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
     }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     // Done : Reset everything for next run
     lockstruct.ans1 = sum;
     lockstruct._lock1 = false;
     goto onestart;
     return 0;
 }
fTHREE()
void * fTHREE (void)
Definition at line 373 of file twz-generator-threaded.c.
References ThreadStruct::_lock3, ThreadStruct::ans3, CALC_PREC, div_power(), lockstruct, mult_power(), number_set, powers, v(), and ThreadStruct::x3.
Referenced by main().
 {
     threestart:
     ;           // This semicolon is required on GCC and ignored elsewhere
     // Wait until the lock is un-set, then run
     do {
         // Do Nothing
     } while (false == lockstruct._lock3);
     int64_t number_set = 2;
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     long double x = lockstruct.x3;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
             last_sum = sum;
             sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
     }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     // Done : Reset everything for next run
     lockstruct.ans3 = sum;
     lockstruct._lock3 = false;
     goto threestart;
     return 0;
 }
fTWO()
void * fTWO (void)
Definition at line 326 of file twz-generator-threaded.c.
References ThreadStruct::_lock2, ThreadStruct::ans2, CALC_PREC, div_power(), lockstruct, mult_power(), number_set, powers, v(), and ThreadStruct::x2.
Referenced by main().
 {
     twostart:
     ;           // This semicolon is required on GCC and ignored elsewhere
     // Wait until the lock is un-set, then run
     do {
         // Do Nothing
     } while (false == lockstruct._lock2);
     int64_t number_set = 1;
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     long double x = lockstruct.x2;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
             last_sum = sum;
             sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
   }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     // Done : Reset everything for next run
     lockstruct.ans2 = sum;
     lockstruct._lock2 = false;
     goto twostart;
     return 0;
 }
get_dtzp()
void get_dtzp (void)
Definition at line 519 of file twz-generator-threaded.c.
References dtzp, and temp.
Referenced by main().
 {
     printf ("Enter the number of days before zero point:  ");
     int64_t temp = scanf ("%Lf", &dtzp);
 }
get_NegBailout()
void get_NegBailout (void)
Definition at line 525 of file twz-generator-threaded.c.
References NegativeBailout, and temp.
Referenced by main().
 {
     printf ("Enter the number of days to calculate after zero point:  ");
     int64_t temp = scanf ("%Lf", &NegativeBailout);
     NegativeBailout *= -1;  // Set to negative for internal use
 }
get_step()
void get_step (void)
Definition at line 532 of file twz-generator-threaded.c.
References inputerror(), step, and temp.
Referenced by main().
 {
     printf ("Enter the time step in minutes ( >= 0 ):  ");
     int64_t temp = scanf ("%Lf", &step);
     step /= 60;         // Convert to 60 minute hours
     step /= 24;         // Convert to fractions of 24-hour days for internal calculations...
     if (step < 0)
         inputerror ();
 }
get_wave_factor()
void get_wave_factor (void)
Definition at line 545 of file twz-generator-threaded.c.
References inputerror(), temp, and wave_factor.
Referenced by main().
 {
     printf ("Enter the wave factor (2-10000) (default 64): ");
     int64_t temp = scanf ("%li", &wave_factor);
     if ( wave_factor < 2 || wave_factor > 10000 )
         inputerror();
 }
inputerror()
void inputerror (void)
Definition at line 563 of file twz-generator-threaded.c.
Referenced by get_step(), get_wave_factor(), and main().
 {
     printf ("\nError: Invalid input, exiting.\n\n");
     exit (EXIT_SUCCESS);
 }
main()
int main (int argc, char * argv[])
Definition at line 158 of file twz-generator-threaded.c.
References ThreadStruct::_lock1, ThreadStruct::_lock2, ThreadStruct::_lock3, ThreadStruct::_lock4, ThreadStruct::ans1, ThreadStruct::ans2, ThreadStruct::ans3, ThreadStruct::ans4, dtzp, fFOUR(), fONE(), fTHREE(), fTWO(), get_dtzp(), get_NegBailout(), get_step(), get_wave_factor(), inputerror(), lockstruct, NegativeBailout, PREC, set_powers(), step, title, usage, wave_factor, ThreadStruct::x1, ThreadStruct::x2, ThreadStruct::x3, and ThreadStruct::x4.
 {
     int64_t i, j, ch;
     if (argc != 5 && argc != 1) {
         printf ("%s", usage);
         inputerror ();
     }
     if (argc == 5) {
         dtzp = atof (&argv[1][0]);
         NegativeBailout = atof (&argv[2][0]);
         NegativeBailout *= -1;
         step = atof (&argv[3][0]);
         step /= 60;     // Convert to 60 minute hours
         step /= 24;     // Convert to 24 hour days
         wave_factor = atoi (&argv[4][0]);
         if (wave_factor < 2 || wave_factor > 10000) {
             printf ("%s", usage);
             inputerror ();
         }
     }
     if (argc == 1) {  // If no commandline inputs
         get_dtzp ();
         get_NegBailout ();
         get_step ();
         get_wave_factor ();
   }
     // Pre-lock all the data locks before spawning the threads, so the threads do not run yet.
     lockstruct._lock1 = lockstruct._lock2 = lockstruct._lock3 = lockstruct._lock4 = false;
     // Declare the thread pointers & start
     pthread_t tONE, tTWO, tTHREE, tFOUR;
     pthread_create (&tONE, NULL, (void *) &fONE, NULL);
     pthread_create (&tTWO, NULL, (void *) &fTWO, NULL);
     pthread_create (&tTHREE, NULL, (void *) &fTHREE, NULL);
     pthread_create (&tFOUR, NULL, (void *) &fFOUR, NULL);
     set_powers ();
     //printf("\n\ndtzp: %lfstep: %lfwave_factor: %d",dtzp, step, wave_factor);
     printf ("\n%s\n", title);
     while (dtzp >= NegativeBailout) {
         printf ("\n%.*Lf ,", PREC, dtzp);
         // populate with the requested date
         lockstruct.x1 = lockstruct.x2 = lockstruct.x3 = lockstruct.x4 = dtzp;
         // Set all the data locks
         lockstruct._lock1 = lockstruct._lock2 = lockstruct._lock3 = lockstruct._lock4 = true;
         // Wait for calculated signal
         while (true == lockstruct._lock1 || true == lockstruct._lock2 || true == lockstruct._lock3 || true == lockstruct._lock4) {
             // Do nothing while waiting, but make progrm wait here
         }
         printf ("%.*Lf ,%.*Lf ,%.*Lf ,%.*Lf ,", PREC, lockstruct.ans1, PREC, lockstruct.ans2, PREC, lockstruct.ans3, PREC, lockstruct.ans4);
         dtzp -= step;
     }
 }
mult_power()
long double mult_power (long double x, int64_t i)
Definition at line 492 of file twz-generator-threaded.c.
References powers.
Referenced by f(), fFOUR(), fONE(), fTHREE(), and fTWO().
 {
     /* Removing this code: Switching to 64-bit datatypes
     int64_t *exponent = (int64_t *) &x + 3;
     if (wave_factor == 64)
         *exponent += i * 0x60;  //  measurably faster
     else */
         x *= powers[i];
     return (x);
 }
set_powers()
void set_powers (void)
Definition at line 230 of file twz-generator-threaded.c.
References NUM_POWERS, powers, and wave_factor.
Referenced by main().
 {
     uint64_t j;
     /*  put powers[j] = wave_factor^j  */
     powers[0] = (long double) 1;
     for (j = 1; j < NUM_POWERS; j++)
         powers[j] = wave_factor * powers[j - 1];
 }
v()
long double v (long double y, int64_t number_set)
Definition at line 469 of file twz-generator-threaded.c.
References NUM_DATA_POINTS, and w.
Referenced by f(), fFOUR(), fONE(), fTHREE(), and fTWO().
 {
     int64_t i = (int64_t) (fmod (y, (long double) NUM_DATA_POINTS));
     int64_t j = (i + 1) % NUM_DATA_POINTS;
     long double z = y - floor (y);
     return (z == 0.0 ? (long double) w[number_set][i] :
         (w[number_set][j] - w[number_set][i]) * z + w[number_set][i]);
 }
Variable Documentation
dtzp
long double dtzp
Definition at line 154 of file twz-generator-threaded.c.
Referenced by doublecheck(), get_dtzp(), and main().
lockstruct
struct ThreadStruct lockstruct
Create a global lock structure to ease programming (4 static threads, so this is OK)
Definition at line 92 of file twz-generator-threaded.c.
Referenced by fFOUR(), fONE(), fTHREE(), fTWO(), and main().
NegativeBailout
long double NegativeBailout = -2.0
Definition at line 94 of file twz-generator-threaded.c.
Referenced by get_NegBailout(), and main().
number_set
int64_t number_set
Definition at line 103 of file twz-generator-threaded.c.
Referenced by fFOUR(), fONE(), fTHREE(), and fTWO().
powers
long double powers[NUM_POWERS]
Definition at line 95 of file twz-generator-threaded.c.
Referenced by div_power(), f(), fFOUR(), fONE(), fTHREE(), fTWO(), mult_power(), and set_powers().
set_name
char* set_name[NUM_SETS]
Initial value:
=
{ "Kelley", "Watkins", "Sheliak", "Huang Ti" }
Definition at line 115 of file twz-generator-threaded.c.
step
long double step
Definition at line 154 of file twz-generator-threaded.c.
Referenced by doublecheck(), get_step(), and main().
stringchar
int64_t stringchar
Definition at line 103 of file twz-generator-threaded.c.
title
char* title = "Days to Zero (DTZ), Kelley, Watkins, Sheliak, Huang Ti"
Definition at line 119 of file twz-generator-threaded.c.
Referenced by main().
usage
char* usage
Initial value:
= "\nUsage: twz [dtz] [neg] [step] [wf]."
"\n dtz = days to zero-point"
"\n neg = days to calcualte into negative-time (past zero)"
"\n step = steps in which to decrement time (in minutes)"
"\n wf = wave factor (default 64, range 2-10000)"
"\n\nThis program calculates the running values of the timewave within the given window.\n"
Definition at line 106 of file twz-generator-threaded.c.
Referenced by main().
w
int64_t w[NUM_SETS][NUM_DATA_POINTS]
Definition at line 123 of file twz-generator-threaded.c.
Referenced by v().
wave_factor
int64_t wave_factor = 64
Definition at line 102 of file twz-generator-threaded.c.
Referenced by get_wave_factor(), main(), and set_powers().