Timewave z3r0: twz-generator.c File Reference
twz-generator.c File Reference
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "DATA/DATA.TW1"
#include "DATA/DATA.TW2"
#include "DATA/DATA.TW3"
#include "DATA/DATA.TW4"
Macros
#define CALC_PREC 1000000
#define FALSE 0
#define NUM_DATA_POINTS 384
#define NUM_POWERS 64
#define NUM_SETS 4
#define PREC 16
#define TRUE 1
Functions
long double div_power (long double x, int64_t i)
int64_t doublecheck (void)
long double f (long double x, int64_t number_set)
long double fFOUR (long double x)
long double fONE (long double x)
long double fTHREE (long double x)
long double fTWO (long double x)
void get_dtzp (void)
void get_NegBailout (void)
void get_step (void)
void get_wave_factor (void)
void inputerror (void)
int main (int argc, char *argv[])
long double mult_power (long double x, int64_t i)
void set_powers (void)
long double v (long double y, int64_t number_set)
Variables
long double dtzp
long double NegativeBailout
int64_t number_set
long double powers [NUM_POWERS]
char * set_name [NUM_SETS]
long double step
int64_t stringchar
char * title = "Days to Zero (DTZ), Kelley, Watkins, Sheliak, Huang Ti"
char * usage
int64_t w [NUM_SETS][NUM_DATA_POINTS]
int64_t wave_factor = 64
Macro Definition Documentation
CALC_PREC
#define CALC_PREC 1000000
Definition at line 62 of file twz-generator.c.
Referenced by f().
FALSE
#define FALSE 0
Definition at line 55 of file twz-generator.c.
NUM_DATA_POINTS
#define NUM_DATA_POINTS 384
Definition at line 61 of file twz-generator.c.
Referenced by v().
NUM_POWERS
#define NUM_POWERS 64
Definition at line 57 of file twz-generator.c.
Referenced by set_powers().
NUM_SETS
#define NUM_SETS 4
Definition at line 60 of file twz-generator.c.
Referenced by main().
PREC
#define PREC 16
Definition at line 58 of file twz-generator.c.
Referenced by main().
TRUE
#define TRUE 1
Definition at line 56 of file twz-generator.c.
Function Documentation
div_power()
long double div_power (long double x, int64_t i)
Definition at line 271 of file twz-generator.c.
References powers.
Referenced by f().
 {
     /* Removing this code: Switching to 64-bit datatypes
     int *exponent = (int *) &x + 3;
     if ((wave_factor == 64) && (*exponent > i * 0x60))
         *exponent -= i * 0x60;
     else */
         x /= powers[i];
     return (x);
 }
doublecheck()
int64_t doublecheck (void)
Definition at line 320 of file twz-generator.c.
References dtzp, and step.
 {
     char answer;
     printf ("\nThe combination you have chosen will create %Lf data points. \nDo you wish to continue? (Y/N) ", 1 + (int) dtzp / step);
     answer = getchar ();
 }
f()
long double f (long double x, int64_t number_set)
Definition at line 199 of file twz-generator.c.
References CALC_PREC, div_power(), mult_power(), powers, and v().
Referenced by main().
 {
     uint64_t i;
     long double sum = 0.0, last_sum = 0.0;
     if (x) {
         for (i = 0; x >= powers[i]; i++)
             sum += mult_power (v (div_power (x, i), number_set), i);
         i = 0;
         do {
             if (++i > CALC_PREC + 2)
                 break;
             last_sum = sum;
             sum += div_power (v (mult_power (x, i), number_set), i);
         } while ((sum == 0.0) || (sum > last_sum));
     }
     /*  dividing by 64^3 gives values consistent with the Apple // version
     *  and provides more convenient y-axis labels
     */
     sum = div_power (sum, 3);
     return (sum);
 }
fFOUR()
long double fFOUR (long double x)
fONE()
long double fONE (long double x)
fTHREE()
long double fTHREE (long double x)
fTWO()
long double fTWO (long double x)
get_dtzp()
void get_dtzp (void)
Definition at line 284 of file twz-generator.c.
References dtzp, and temp.
Referenced by main().
 {
     printf ("Enter the number of days before zero point:  ");
     int64_t temp = scanf ("%Lf", &dtzp);
 }
get_NegBailout()
void get_NegBailout (void)
Definition at line 290 of file twz-generator.c.
References NegativeBailout, and temp.
Referenced by main().
 {
     printf ("Enter the number of days to calculate after zero point:  ");
     int64_t temp = scanf ("%Lf", &NegativeBailout);
     NegativeBailout *= -1;  // Set to negative for internal use
 }
get_step()
void get_step (void)
Definition at line 299 of file twz-generator.c.
References inputerror(), step, and temp.
Referenced by main().
 {
     printf ("Enter the time step in minutes ( >= 0 ):  ");
     int64_t temp = scanf ("%Lf", &step);
     step /= 60;         // Convert to 60 minute hours
     step /= 24;         // Convert to fractions of 24-hour days for internal calculations...
     if (step < 0)
         inputerror ();
 }
get_wave_factor()
void get_wave_factor (void)
Definition at line 311 of file twz-generator.c.
References inputerror(), temp, and wave_factor.
Referenced by main().
 {
     printf ("Enter the wave factor (2-10000) (default 64): ");
     int64_t temp = scanf ("%ld", &wave_factor);
     if ( wave_factor < 2 || wave_factor > 10000 ) inputerror();
 }
inputerror()
void inputerror (void)
Definition at line 328 of file twz-generator.c.
Referenced by get_step(), get_wave_factor(), and main().
 {
     printf ("\nError: Invalid input, exiting.\n\n");
     exit (EXIT_SUCCESS);
 }
main()
int main (int argc, char * argv[])
Definition at line 128 of file twz-generator.c.
References dtzp, f(), get_dtzp(), get_NegBailout(), get_step(), get_wave_factor(), inputerror(), NegativeBailout, NUM_SETS, number_set, PREC, set_powers(), step, title, usage, and wave_factor.
 {
     int64_t i, j, ch;
     if (argc != 5 && argc != 1) {
         printf ("%s", usage);
         inputerror ();
     }
     if (argc == 5) {
         dtzp = atof (&argv[1][0]);
         NegativeBailout = atof (&argv[2][0]);
         NegativeBailout *= -1;
         step = atof (&argv[3][0]);
         step /= 60;     // Convert to 60 minute hours
         step /= 24;         // Convert to 24 hour days
         wave_factor = atoi (&argv[4][0]);
         if (wave_factor < 2 || wave_factor > 10000) {
             printf ("%s", usage);
             inputerror ();
         }
     }
     if (argc == 1) {        // If no commandline inputs
         get_dtzp();
         get_NegBailout();
         get_step();
         get_wave_factor();
     }
     set_powers();
     //printf("\n\ndtzp: %lfstep: %lfwave_factor: %d",dtzp, step, wave_factor);
     printf ("\n%s\n", title);
     while (dtzp >= NegativeBailout) {
         printf ("%.*Lf ,", PREC, dtzp);
         for (number_set = 0; number_set < NUM_SETS; number_set++) {
             printf ("%.*Lf ,", PREC, f (dtzp, number_set));
         }
         printf ("\n");
         dtzp -= step;
     }
 }
mult_power()
long double mult_power (long double x, int64_t i)
Definition at line 256 of file twz-generator.c.
References powers.
Referenced by f().
 {
     /* Removing this code: Switching to 64-bit datatypes
     int *exponent = (int *) &x + 3;
     if (wave_factor == 64)
         *exponent += i * 0x60; //   measurably faster
     else
     */
         x *= powers[i];
     return (x);
 }
set_powers()
void set_powers (void)
Definition at line 184 of file twz-generator.c.
References NUM_POWERS, powers, and wave_factor.
Referenced by main().
 {
     uint64_t j;
     /*  put powers[j] = wave_factor^j  */
     powers[0] = (long double) 1;
     for (j = 1; j < NUM_POWERS; j++)
         powers[j] = wave_factor * powers[j - 1];
 }
v()
long double v (long double y, int64_t number_set)
Definition at line 232 of file twz-generator.c.
References NUM_DATA_POINTS, and w.
Referenced by f().
 {
     int64_t i = (int64_t) (fmod (y, (long double) NUM_DATA_POINTS));
     int64_t j = (i + 1) % NUM_DATA_POINTS;
     long double z = y - floor (y);
     return (z == 0.0 ? (long double) w[number_set][i] :
         (w[number_set][j] - w[number_set][i]) * z + w[number_set][i]);
 }
Variable Documentation
dtzp
long double dtzp
Definition at line 124 of file twz-generator.c.
Referenced by doublecheck(), get_dtzp(), and main().
NegativeBailout
long double NegativeBailout
Definition at line 124 of file twz-generator.c.
Referenced by get_NegBailout(), and main().
number_set
int64_t number_set
Definition at line 73 of file twz-generator.c.
Referenced by main().
powers
long double powers[NUM_POWERS]
Definition at line 65 of file twz-generator.c.
Referenced by div_power(), f(), mult_power(), and set_powers().
set_name
char* set_name[NUM_SETS]
Initial value:
=
{ "Kelley", "Watkins", "Sheliak", "Huang Ti" }
Definition at line 84 of file twz-generator.c.
step
long double step
Definition at line 124 of file twz-generator.c.
Referenced by doublecheck(), get_step(), and main().
stringchar
int64_t stringchar
Definition at line 73 of file twz-generator.c.
title
char* title = "Days to Zero (DTZ), Kelley, Watkins, Sheliak, Huang Ti"
Definition at line 88 of file twz-generator.c.
Referenced by main().
usage
char* usage
Initial value:
= "\nUsage: twz [dtz] [neg] [step] [wf]."
"\n dtz = days to zero-point"
"\n step = steps in which to decrement time (in minutes)"
"\n wf = wave factor (default 64, range 2-10000)"
"\n\nThis program calculates the running values of the timewave within the given window.\n"
Definition at line 76 of file twz-generator.c.
Referenced by main().
w
int64_t w[NUM_SETS][NUM_DATA_POINTS]
Definition at line 92 of file twz-generator.c.
Referenced by v().
wave_factor
int64_t wave_factor = 64
Definition at line 72 of file twz-generator.c.
Referenced by get_wave_factor(), main(), and set_powers().